@startuml
'https://plantuml.com/class-diagram
skinparam groupInheritance 2

skinparam linetype polyline

package Board
{
     class Board {
     -ALL_SQUARES : square[]
     -ACTIONHANDLER : ActionHandler
     -jailposition : int

    -payStartBonus(Player) : void
    -stringArrayToIntArray(String[], size:int) : int[]
    +hasMonopoly() : boolean
    +movePlayer(Player, spacesToMove:int) : void
    +setPlayerPosition(Player, position:int) : void

    }
     abstract class Square {
         -name : String
         -position : int
     }
     class Street{
        -amountOfHouses : int

     }
     abstract class Ownable{
        -COLOR : String
        -PRICE : int
        -RENT : int[]
        -owner : Player
        -pledge : boolean
     }
     class incomeTax{
       AMOUNT : int
       PERCENTAGE : int
     }
     class Tax{
        -AMOUNT : int
     }
     class Ferry{
     }
     class Brewery{
     }
     class GoToPrison{
     }
     class Prison{
     }
     class Refugee{
     }
     class Start{
     }
     class Chance{
     }
}

Board "1  "  *--d- "1..40" Square: Has

Ownable "1     " <|--- "22" Street : Is\t
Ownable "1" <|--- " 4    " Ferry : Is \t
Ownable "           1" <|--- " 2" Brewery : Is\t


Square <|-- "1" Tax
Square <|-- Ownable
Square <|-- "1" incomeTax
Square <|-- "           1" Start
Square <|-- "             1" Refugee
Square <|-- "1" GoToPrison: \t Is a    \t
Square <|-- "             1" Prison
Square <|--  "            6" Chance

GameController *-- Board
ActionHandler --* Board



@enduml