@startuml
'https://plantuml.com/class-diagram
skinparam groupInheritance 2

skinparam linetype polyline

package Board
{
     class Board {
     -ALL_SQUARES : square[]
     -ACTIONHANDLER : ActionHandler
     -jailposition : int

     -stringArrayToIntArray(String[] arr, String type): int[]
     -reduceStringArraySize(String[] arr, int size): String[]
     -calculateSpaceToMove(int startPosition, int endPosition): int
     -payStartBonus(Player currentPlayer): void
     -amountOwnedWithinTheColor(int position): int
     -hasMonopoly(int position, Player... player): boolean
     -ensureEvenDistribution(int position, boolean buy): boolean
     +updatePlayerPosition(Player player, int diceValue): void
     +setPlayerPosition(Player player, int endPos, boolean goingToJail): void
     +setPlayerInJail(Player player): void
     +escapeJail(Player player, int dieRoll, boolean forcedToMove, boolean haveToPay, boolean usedChanceCard): void
     +getCurrentCost(int position): int
     +playerTotalValue(Player player): int
     +buyHouse(Player player, String color, int amountOfHouses): void
     +buyHotel(Player player, String color, int amountOfHotels): void
     +sellBuilding(Player player, String color, String type, int amount): void
     +aLlSquaresWherePlayerHaveHouses(Player player): String[]
     +allMonopolyColorsByPlayer(Player player): String[]
     +getAllStreetColors(): String[]
     +getHousePrice(String color): int
     +amountOfHousesOnColor(String color): int
     +allSquaresOwnedByPlayer(Player player): String[]
     +playerGoingBankrupt(Player player): void
     +givePlayerToActionHandler(Player[] players): void






    }
     abstract class Square {
         -name : String
         -position : int
     }
     class Street{
        -HOUSEPRICE: int
        -amountOfHouses : int

     }
     abstract class Ownable{
        -COLOR : String
        -PRICE : int
        -RENT : int[]
        -owner : Player
        -pledge : boolean
     }
     class incomeTax{
       AMOUNT : int
       PERCENTAGE : int
     }
     class Tax{
        -AMOUNT : int
     }
     class Ferry{
     }
     class Brewery{
     }
     class GoToPrison{
     }
     class Prison{
     }
     class Refugee{
     }
     class Start{
     }
     class Chance{
     }
}

Board "1  "  *--d- "1..40" Square: Has

Ownable "1     " <|--- "22" Street : Is\t
Ownable "1" <|--- " 4    " Ferry : Is \t
Ownable "           1" <|--- " 2" Brewery : Is\t


Square <|-- "1" Tax
Square <|-- Ownable
Square <|-- "1" incomeTax
Square <|-- "           1" Start
Square <|-- "             1" Refugee
Square <|-- "1" GoToPrison: \t Is a    \t
Square <|-- "             1" Prison
Square <|--  "            6" Chance

GameController <-- Board
ActionHandler --> Board
CSVReader --> Board


@enduml