@startuml
'https://plantuml.com/class-diagram
skinparam groupInheritance 2

skinparam linetype polyline

package Board
{
     class Board {
    }
     abstract class Square {
     }
}
package Cards
{
   abstract class chanceCard{
   }
   class Deck{
   }
   class ChanceCardLogic{
   }

}

package Logic{
     class Player{
     }
     class Die {
     }

     class DiceCup {
     }
     class Bank {
     }
     class ActionHandler {
     }
     class GameController {
     }
}
package Interface{
class GUIController{

}

}
package Utilities
{
  class CSVReader{
  }
  class Language{
  }
}



GameController -u- GUIController
Bank -u- ActionHandler
GameController -- DiceCup
DiceCup -- Die
GameController -d- Player

ActionHandler -d- Deck
GameController <-u- Board
Board *-d- Square


Deck -- ChanceCardLogic
ChanceCardLogic -- chanceCard


Board -u- CSVReader
Board <- ActionHandler
CSVReader -- Language






@enduml