@startuml

object Board
object Player
object Die
object "Dice Cup" as diceCup
object Bank
object "Chance Card" as chance
object Deck
object Square
object Matador

Die : FaceValue
Player : Name
Player : Balance
Player : Position
chance : Description
Square : Name
Square : Rents
Square : Owner

Matador "1" -r- "3..6" Player : \t Plays \t
Matador "1" -u- "1 " Bank : Deals With

Matador "1  " -u- "1" diceCup : Holds
diceCup "1" -u- "2" Die : Rolls

Deck "1" -l- "28" chance : \t Holds \t
Matador "1" -l- "1" Deck : \t Is on \t

Board "1" -u- "1" Matador : Played On
Board "1" -d- "40" Square : Consists Of\t

@enduml