@startuml

object Board
object Player
object Die
object "Dice Cup" as dicecup
object Bank
object "Chance Card" as chance
object Deck
object Square
object Deed

Die : FaceValue
Player : Name
Player : Balance
chance : Description
Deed : Cost
Deed : Rent
Deed : Pledge Value
Square : Name

Board "1" -r- "3..6" Player : \t Plays \t
Player "3..6" -r- "1" Bank : \t Manages \t

Board "1" -u- "1" dicecup : Rolls
dicecup "1" -u- "2" Die : Holds

Deck "1" -l- "28" chance : \t Holds \t
Board "1" -l- "1" Deck : \t Is on \t

Board "1" -d- "40" Square : Consists Of\t

Square "1" -r- "0..1" Deed : \t Has \t\t\t
Bank "0..1    " -- "     0..22" Deed : Owns
Player "0..1" -- "0..22" Deed : Owns

@enduml