@startuml
'https://plantuml.com/class-diagram
skinparam groupInheritance 2

skinparam linetype polyline

package Interface{
class GUIController{
      {static} -testing : boolean
      {static} -gui : GUI
      {static} -fields : Square[]
      {static} -GUIFields : GUI_Field[]
      {static} -playersNames : String[]
      {static} -guiPlayers : GUI_Plaers[]
      {static} -colorToChooseFrom : Color[]
      {static} -moveTime : int

      {static} +createBoard(Square[] inputSquares): GUI_FIELD
      {static} +createPlayers(int startBalance): void
      {static} +movePlayer(Player player, int destination: void)
      {static} +showDice(int[] facevalues): void
      {static} +setHouses(int position, int amount): void
      {static} +setHotel(int position, boolean bool): void
      {static} +setOwner(Player player, int position): void
      {static} +updateRent(int position): void
      {static} +givePlayerChoice(String msg, String[] choices): String
      {static} +askPlayerAccept(String msg): boolean
      {static} +showCenterMessage(String msg): void
      {static} +showMessage(String msg): void
      {static} +posToStreet(int position): GUI_Street
      {static} +convertColor(String colorStr): Color
}



@enduml